# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "items", :force => true do |t|
    t.column "title", :string
  end

  create_table "purchases", :force => true do |t|
    t.column "request_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "user_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "item_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "created_at", :timestamp
    t.column "cost", :float
  end

  add_index "purchases", ["user_id"], :name => "purchases_FKIndex1"
  add_index "purchases", ["item_id"], :name => "purchases_FKIndex2"
  add_index "purchases", ["request_id"], :name => "purchases_FKIndex3"

  create_table "requests", :force => true do |t|
    t.column "user_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "item_id", :integer, :limit => 10, :default => 0, :null => false
    t.column "created_at", :timestamp
    t.column "updated_at", :timestamp
    t.column "quantity", :float
  end

  add_index "requests", ["item_id"], :name => "requests_FKIndex1"
  add_index "requests", ["user_id"], :name => "requests_FKIndex2"

  create_table "users", :force => true do |t|
    t.column "username", :string, :limit => 50
    t.column "passwd", :string, :limit => 42
  end

end
